### ISSUE TITLE
Encoding not declared for db update

### ISSUE THREAD

**Issue by talexand** [leoboiko/myougiden#4]
Ubuntu 14.04, pip 1.5.4, python 2., ja-JP locale:

Ran `sudo updatedb-myougiden -f` and `sudo updatedb-myougiden` with same result:
```
  File "/usr/local/bin/updatedb-myougiden", line 29
SyntaxError: Non-ASCII character '\xc5' in file /usr/local/bin/updatedb-myougiden on line 29, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

**Comment by talexand** [comment]
Inserting the following encoding declaration into the file helps:

```
#!/usr/bin/python
# -*- coding: utf-8-unix
```
(saved with the above encoding)

This leads to another error:

```
  File "/usr/local/bin/updatedb-myougiden", line 462
    nonlocal count
                 ^
SyntaxError: invalid syntax
```

**Comment by leoboiko** [comment]
It seems your system is calling myougiden with python 2.x , even though the script line says

    #!/usr/bin/env python3

Do you have any idea why? I'll see if I can get my hands on an Ubuntu and test it…

**Comment by talexand** [comment]
Hmm. I tried changing the first line to `#!/usr/bin/env python3` and got an error:
```
➤ updatedb-myougiden 
Traceback (most recent call last):
  File "/usr/local/bin/updatedb-myougiden", line 19, in <module>
    from myougiden import config
ImportError: No module named 'myougiden'
```

**Comment by leoboiko** [comment]
That probably means the `pip install` command installed it for Python 2, rather than Python 3.  Do you have a `pip3` command or similar?

It's possible that my pips are broken, and anyway the git source has some interesting new optimizations that I failed to release.  Thanks for reporting issues! Right now I'm drowned in things to do, but it's about time to package a new pip.  I'll try to come up with something this weekend.

**Comment by talexand** [comment]
You're exactly right. You have to explicitly specify `pip3`. Sorry about that; I should have obeyed the README better.
