### ISSUE TITLE
Daemon mode?

### ISSUE THREAD

**Issue by fasiha** [leoboiko/myougiden#5]
I love myougiden, it's my favorite way to search JMdict, to the point that my software projects just shell out to it instead of dealing with the official XML file. Sometimes, I have a list of hundreds or thousands of words to compile glosses for. In cases like this, how substantial would you guess overhead is for, first, Python initializing and second, the database loading from disk? Would it make sense to try and daemonize myougiden so it initialized and then just waited for queries, and stayed alive rather than shutting down after answering them?

(The queries could come over a fancy REST interface through a webserver, or really anything.)

**Comment by leoboiko** [comment]
My kernel programming friend tells me that a modern system should cache
things efficiently enough that the .sqlite DB file would be in-memory after
a couple calls, so that daemonization would change little, if anything.

A python3 helloworld takes 0.01s on my old laptop, according to time(1).

The majority of myougiden's time is spent searching stuff. The current git
version, whose release I've been procrastinating, includes a full-text
search mode, which had significant impact on guess-search.

But if all you need are pairs of word:glosses, it's hard to beat a custom
indexed db. It should be simple to write a script to extract the pairs from
the XML, or even old-format edict, and write out a .sql.

Also, depending on the application, consider whether you want the
autogenerated glosses of a morphological analyzer like Mecab or Kytea (good
when you have a full, grammatical text to analyze, and it's hard to say
where things begin and end).

Thanks for your support!
2015/05/22 21:43 "Ahmed Fasih" <notifications@github.com>:

**Comment by fasiha** [comment]
Thanks for the super-thoughtful and practical reply! Since I read it a couple of days ago, I've forgotten about daemon mode, cut out the parts of the XML file that I cared about into JSON and treated it as an in-memory db (more than fast enough for full-text searches on headwords), and I'm about to try out KyTea (never heard of it before, though I've played with MeCab a good deal).
